# Installing NumPy

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [3]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [6]:
print(a[0])

[1 2 3 4]


In [7]:
[[0., 0., 0.],
 [1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

In [8]:
import numpy as np
a = np.array([1, 2, 3])

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.ones(2)

array([1., 1.])

In [11]:
np.empty(2)

array([1., 1.])

In [12]:
np.arange(4)

array([0, 1, 2, 3])

In [13]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [14]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

# Adding, removing, and sorting elements

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [17]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([1, 2, 3, 4])
print(a)
b = np.array([5, 6, 7, 8])
print(b)

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 9])

In [27]:
x = np.array([[1, 2], [3, 4]])
print(x)
y = np.array([[5, 6]])
print(y)

[[1 2]
 [3 4]]
[[5 6]]


In [28]:
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array

In [32]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [33]:
array_example.ndim

3

In [34]:
array_example.size

24

In [35]:
array_example.shap

(3, 2, 4)

# Can you reshape an array?

In [40]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [41]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis,:]
a2

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a2.shape

(1, 6)

In [ ]:
a3 = a[np.newaxis, :3] # 3열만 가져와서 차원 추가
a3

array([[0, 1, 2]])

In [ ]:
a4 = a[:,np.newaxis] #
a4

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### indexing and slicing

In [ ]:
data = np.array([1, 2, 3])

In [ ]:
data

array([1, 2, 3])

In [ ]:
data[2]

3

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [ ]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a [ a < 5 ]

array([1, 2, 3, 4])

In [ ]:
a [ a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a [ a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [114]:
c = a[(a > 2) & (a < 11)]
print(c)

five_up = (a > 5) | (a == 5)
print(five_up)

[]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True]


In [115]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [252]:
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

print(a[b])

not_there = np.nonzero(a == 42)
print(not_there)

(1, 2)
(1, 2)
[[11 11]
 [12 12]]
(array([], dtype=int64),)


### How to create an array for existing data

In [253]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [254]:
arr1 = a[3:8]

In [255]:
arr1

array([4, 5, 6, 7, 8])

In [256]:
a1 = np.array([[1, 1],
              [2, 2]])
a2 = np.array([[3, 3],
              [4, 4]])

In [257]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [258]:
np.concatenate((a1, a2), axis=0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [259]:
np.concatenate((a1, a2), axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [260]:
x = np.arange(1, 25).reshape(2, 12)

In [261]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [262]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [263]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [264]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [265]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [268]:
b1 = a[0,:]
b1

array([1, 2, 3, 4])

In [269]:
b1[0] = 99

In [270]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [271]:
b2 = a.copy()

In [272]:
b2[1,1] = 7
b2

array([[99,  2,  3,  4],
       [ 5,  7,  7,  8],
       [ 9, 10, 11, 12]])

In [273]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### basic array operations

In [274]:
data = np.array([1, 2])

In [275]:
ones = np.ones(2, dtype = int)

In [276]:
data + ones

array([2, 3])

In [277]:
a = np.array([1, 2, 3, 4])

In [278]:
a.sum()

10

In [279]:
b = np.array([[1, 1],[2, 2]])

In [280]:
b.sum()

6

In [281]:
b.sum(axis=0)

array([3, 3])

In [282]:
b.sum(axis=1)

array([2, 4])

# Broadcasting

In [320]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

### More useful array operations

In [321]:
data.max()

2.0

In [322]:
data.sum()

3.0

In [323]:
data.min()

1.0

In [324]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [358]:
a.sum()

216

In [359]:
a.min()

11

In [360]:
a.min(axis=0) # 행 중에서 가장 작은애를 찾는다? 실제는 같은 열에서 작은 애를 찾는 결과. 이정도면 axis=0은 열기준으로 외우는게 낫지않을까?

11

### Creating matrics

In [361]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [362]:
data[0, 1]

2

In [363]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [364]:
data[0:2, 0]

array([1, 3])

In [365]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [366]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [367]:
data.max(axis=0)

array([5, 6])

In [368]:
data.max(axis=1)

array([2, 5, 6])

In [369]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [370]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [392]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [436]:
print(np.ones(3))

print(np.zeros(3))

rng = np.random.default_rng()  # the simplest way to generate random numbers
print(rng.random(3))

[1. 1. 1.]
[0. 0. 0.]
[0.15818554 0.83930301 0.26109544]


In [480]:
print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(rng.random((3, 2)) )


[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.14448738 0.80660359]
 [0.86538582 0.57730357]
 [0.81731865 0.38649175]]


# Generating random numbers

In [481]:
rng.integers(5, size=(2, 4))

array([[2, 4, 1, 0],
       [2, 0, 2, 2]])

### How to get unique items and counts

In [482]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [483]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [484]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [499]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [518]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [537]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [556]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [575]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


### Transposing and reshaping a matrix

In [576]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [577]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [578]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [579]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [580]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### How to reverse an array

In [581]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [582]:
reversed_arr = np.flip(arr)

In [583]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [584]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [585]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [586]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [587]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [588]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [589]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


## Reshaping and flattening multidimensional arrays

In [590]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [591]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [592]:
a1 = x.flatten()
a1[0] = 99
print(x)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [593]:
a2 = x.ravel()
a2[0] = 98
print(x)
print(a2)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
